name: Kubernetes App Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'k8s/**'
      - 'monitoring/**'
      - '.github/workflows/k8s-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: devops-eks-cluster

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s/
          kubectl apply -f monitoring/prometheus/
          kubectl apply -f monitoring/grafana/

